### ISSUE TITLE
Unexpected training performance with latest version

### ISSUE THREAD

**Issue by fthdrsn** [blg604-proje/blg604-proje#7]
Hi,
I have weird results when training with latest python API. I have used different algorithms with previous version of python API and got stable results. But I got way worse results when retrained with latest version. I couldn’t figure it out what caused that drastic performance decreasing (Especially,the car is very slow(max speed: 40km/h)).   I wonder , what was changed in SimstarEnv.py and changing hz property can cause that issue ? Thanks for your help.

**Comment by ferhatmelih** [comment]
Syncronized mode makes deterministic training. So addition of Hz(environment sampling) makes the simulation sampling frequency (in simulation time) the same every time. We expect that if you train and test your algorithms at the same sampling period, they should turn out to be the same. 

You can try this, measure the environment sampling frequency in the scenario that you get successful result and please report here. It should be

`number of times **env.step()** is called in a second.`

And then set the environment sampling to that value. In our tests, we found 10 Hz to be optimal and decided that this should be the standart. 

If for example you get the best results with 5 Hz or 2Hz. You can skip action calculation in evaluation. If it is a higher frequency than 10 we can discuss that again. Please share your results.

**Comment by fthdrsn** [comment]
I get successful results with speed_up=5 and hz=6. For this scenario, I measured sampling frequency as around 24 Hz. For speed_up=1 and hz=30, I get same sampling frequency. Then changed my setup to speed_up=6 and hz=10. I get 32 Hz frequency. This shows that my algorithm is not fast enough to sample with 60 Hz frequency. As I understand, sampling frequency depends on both speed_up and hz. I trained my model with Hungary and Dutch tracks (speed_up=5, hz=6 ) and tested with same tracks. Firstly, I set  speed_up=1, hz=6 and 30 for evaluation. For speed_up=1 and hz=30, I get better results.
According to these results, should I select (speed_up*hz) value to be less than 10 in training for 
suitability with fixed evaluation frequency or select hz value regardless of speed_up or my results are wrong :)

**Comment by ferhatmelih** [comment]
Hi, thanks for the detailed analysis. It is helpful. 

We have a fixed step size simulator that is fixed at 60 frame per second, FPS. A brief explanation was provided in this [ReadMe](https://github.com/blg604-proje/blg604-proje/tree/master/GymEnv).

Fixed frame rate means that, even if the simulator runs at 10 FPS (in case hardware is not powerful), the time between each frame is the same in simulation time, 1/60 seconds. This gives us determinism across devices.   

Therefore, 60 FPS sets our maximum sampling. If we choose a factor of 60, like 10hz: then at each **env.step()** we pass 60/10=6 frames in the simulator. Now, if we **speed-up 2x** times, then for each simulation frame, time passes 2x times the normal time. Therefore we should sample 6/2 = 3  frames in each **env.step()**, so our environment gets the **same simulation time difference** between the steps.  

Following this logic, your _Hz * speed_up_ should always be a factor of 60. 

| Sampling Freq of Env       | Speed-up           | Num Frames in env.step()  |
| ------------- |:-------------:| -----:|
| 5 Hz    | 1x  | 12  |
| 5Hz      | 6x      |   2  |
| 10 Hz | 1x      |    6 |

Since evaluation of each agent will be done separately, as decided by professor, you can choose the sampling Hz to the value that best fits your performance. 

If I didn't explain clear enough, please feel free to ask.

**Comment by firatoncel** [comment]
According to our experience, it is far more easy to develop model at higher update frequencies. For us, it was quite challenging to develop a successful model at 10 Hz. Therefore, we think that it is not fair to change this evaluation criteria when it is this much close to the competition.

**Comment by ferhatmelih** [comment]
Lets open this issue to the professor and let him decide on that.

**Comment by fthdrsn** [comment]
Thanks for the detailed explanation.

**Comment by ferhatmelih** [comment]
@firatoncel @fthdrsn we just discussed with the professor that the evaluation maximum sampling frequency is set to 10 Hz. Anything below that is acceptable, but you cannot go higher.
